"use strict";

export const LOCATION_CHANGE = "@@router/LOCATION_CHANGE";

// global

export const CLOSE_MODAL = "CLOSE_MODAL";
export const OPEN_MODAL = "OPEN_MODAL";

export const POLL_CONFIG = "POLL_CONFIG";
export const RESET_STATE = "RESET_STATE";
export const SET_CONFIG_DATA = "SET_CONFIG_DATA";
export const SET_GLOBAL_COUPON = "SET_GLOBAL_COUPON";
export const SET_PRIMARY_NAV = "SET_PRIMARY_NAV";
export const SET_SECONDARY_NAV = "SET_SECONDARY_NAV";
export const SET_MOBILE_NAV = "SET_MOBILE_NAV";
export const UPDATE_CONFIG = "UPDATE_CONFIG";

// Authentication

export const FETCH_ME = "FETCH_ME";
export const LOGOUT = "LOGOUT";
export const SET_TOKEN = "SET_TOKEN";
export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_RESP = "SIGN_IN_RESP";
export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_RESP = "SIGN_UP_RESP";
export const VERIFY_ACCOUNT = "VERIFY_ACCOUNT";

// Search

export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const SET_SEARCH_VISIBILITY = "SET_SEARCH_VISIBILITY";

// Cookies

export const SET_COOKIE = "SET_COOKIE";
export const SET_LOCAL_STORAGE = "SET_LOCAL_STORAGE";
export const UPDATE_STATE_WITH_COOKIE = "UPDATE_STATE_WITH_COOKIE";
export const UPDATE_STATE_WITH_LOCALSTORAGE = "UPDATE_STATE_WITH_LOCALSTORAGE";

// Products

export const FETCH_ALL = "FETCH_ALL";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_RESP = "FETCH_PRODUCTS_RESP";
export const SET_PURCHASED_PRODUCTS = "SET_PURCHASED_PRODUCTS";

// Order

export const ADD_COUPON = "ADD_COUPON";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const ADD_SHIP_ADDRESS_TO_ORDER = "ADD_SHIP_ADDRESS_TO_ORDER";
export const APPLY_COUPON_TO_ORDER = "APPLY_COUPON_TO_ORDER";
export const CALCULATE_TOTAL = "CALCULATE_TOTAL";
export const CALCULATE_TOTAL_RESP = "CALCULATE_TOTAL_RESP";
export const CANCEL_ORDER = "CANCEL_ORDER";
export const CANCEL_ORDER_RESP = "CANCEL_ORDER_RESP";
export const CLEAR_ACTIVE_ORDER = "CLEAR_ACTIVE_ORDER";
export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_FOR_CART = "CREATE_ORDER_FOR_CART";
export const CREATE_ORDER_RESP = "CREATE_ORDER_RESP";
export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART";
export const PATCH_ORDER = "PATCH_ORDER";
export const SET_ACTIVE_ORDER = "SET_ACTIVE_ORDER";
export const SET_PENDING_ORDER_CHECK_FLAG = "SET_PENDING_ORDER_CHECK_FLAG";
export const SET_PENDING_ORDER_VISIT_FLAG = "SET_PENDING_ORDER_VISIT_FLAG";
export const SET_PENDING_ORDER_REVIEW_NEEDED_FLAG =
  "SET_PENDING_ORDER_REVIEW_NEEDED_FLAG";
export const UPDATE_ITEM_IN_ORDER = "UPDATE_ITEM_IN_ORDER";
export const UPDATE_ITEM_IN_ORDER_RESP = "UPDATE_ITEM_IN_ORDER_RESP";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const UPDATE_ORDER_RESP = "UPDATE_ORDER_RESP";

// User

export const FETCH_ADDRESSES = "FETCH_ADDRESSES";
export const FETCH_ADDRESSES_RESP = "FETCH_ADDRESSES_RESP";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_RESP = "UPDATE_USER_RESP";

// EMR

export const FETCH_VISITS = "FETCH_VISITS";
export const FETCH_VISITS_RESP = "FETCH_VISITS_RESP";
export const HIDE_EMR_FORM = "HIDE_EMR_FORM";
export const PATIENT_CONSENTED = "PATIENT_CONSENTED";
export const RESET_EMR_FORMS = "RESET_EMR_FORMS";
export const SET_ACTIVE_VISIT = "SET_ACTIVE_VISIT";
export const SET_QUESTIONNAIRE = "SET_QUESTIONNAIRE";
export const SHOW_EMR_FORM = "SHOW_EMR_FORM";
export const SUBMIT_EMR_FORM = "SUBMIT_EMR_FORM";
export const UPDATE_VISIT = "UPDATE_VISI2";
export const PHOTO_UPLOAD_SUCCESS = "PHOTO_UPLOAD_SUCCESS";

// Checkout

export const UPDATE_CHECKOUT_STEP = "UPDATE_CHECKOUT_STEP";

// Drawer

export const HIDE_LEFT_DRAWER = "HIDE_LEFT_DRAWER";
export const HIDE_RIGHT_DRAWER = "HIDE_RIGHT_DRAWER";
export const HIDE_TOP_DRAWER = "HIDE_TOP_DRAWER";
export const OPEN_RIGHT_DRAWER = "OPEN_RIGHT_DRAWER";
export const RENDER_DRAWER = "RENDER_DRAWER";
export const SET_LEFT_DRAWER = "SET_LEFT_DRAWER";
export const SET_RIGHT_DRAWER = "SET_RIGHT_DRAWER";
export const SET_RIGHT_DRAWER_EMR_CLOSING = "SET_RIGHT_DRAWER_EMR_CLOSING";
export const SET_TOP_DRAWER = "SET_TOP_DRAWER";
export const SHOW_LEFT_DRAWER = "SHOW_LEFT_DRAWER";
export const SHOW_RIGHT_DRAWER = "SHOW_RIGHT_DRAWER";
export const SHOW_TOP_DRAWER = "SHOW_TOP_DRAWER";
export const RESET_DRAWER_TO_DEFAULT = "RESET_DRAWER_TO_DEFAULT";

// Messages

export const MARK_MESSAGE_AS_READ = "MARK_MESSAGE_AS_READ";
export const MARK_MESSAGE_AS_READ_RESP = "MARK_MESSAGE_AS_READ_RESP";
export const SET_ACTIVE_MESSAGE = "SET_ACTIVE_MESSAGE";
export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const UPDATE_MESSAGE_RESP = "UPDATE_MESSAGE_RESP";

// Subscription
export const DISMISS_REACTIVATE_SUBSCRIPTION_PROMPT =
  "DISMISS_REACTIVATE_SUBSCRIPTION_PROMPT";
export const UPDATE_SUBSCRIPTION_BY_ID = "SUBSCRIPTIONS:UPDATE_BY_ID";

// Reviews
export const FETCH_REVIEWS_BOTTOM_LINE = "FETCH_REVIEWS_BOTTOM_LINE";

// Renewals
export const START_RENEWAL_EMR_VISIT = "START_RENEWAL_EMR_VISIT";

// Blog
export const RESET_ACTIVE_BLOG = "RESET_ACTIVE_BLOG";
export const RESET_ACTIVE_BLOGS = "RESET_ACTIVE_BLOGS";

// UI
export const SHOW_DRAWER = "SHOW_DRAWER";
export const SHOW_DRAWER_CART_OR_FINAL_REVIEW =
  "SHOW_DRAWER_CART_OR_FINAL_REVIEW";
export const HIDE_DRAWER = "HIDE_DRAWER";

// UI - PDP
export const PDP_SCROLL_TO_SAFETY_INFORMATION =
  "PDP_SCROLL_TO_SAFETY_INFORMATION";
export const PDP_SAFETY_INFORMATION_SWITCH_TEXT_CLOSED_STATE =
  "PDP_SAFETY_INFORMATION_SWITCH_TEXT_CLOSED_STATE";

// UI - Coupon Banner
export const DISMISS_COUPON_BANNER = "DISMISS_COUPON_BANNER";

// Cart

export const RESET_CART = "RESET_CART";
