"use strict";

const ORDER_STEPS = {
  PENDING_EMR: "PENDING_EMR",
  ORIGIN: "ORIGIN",
  PAYMENT: "PAYMENT",
  EMR: "EMR",
  PHARMACY: "PHARMACY",
  SHIPPING: "SHIPPING",
  CUSTOMER: "CUSTOMER",
  SHIPPED: "SHIPPED",
  SUBMITTED: "SUBMITTED",
  CANCELLED: "CANCELLED"
};

const ORDER_STATUSES = {
  PENDING: "pending",
  SUBMITTED: "submitted",
  CANCELLED: "cancelled"
};

const SHIPPING_STATUSES = {
  DELIVERED: "DELIVERED",
  FAILURE: "FAILURE",
  RETURNED: "RETURNED",
  TRANSIT: "TRANSIT",
  UNKNOWN: "UNKNOWN"
};

const SHIPPING_STATUS = [
  "DELIVERED",
  "FAILURE",
  "RETURNED",
  "TRANSIT",
  "UNKNOWN"
];

const EMR_STATUSES = {
  CLOSED: "closed",
  CANCELLED: "cancelled",
  ANSWERED: "answered",
  PENDING: "pending"
};

const SUBSCRIPTION_STATUSES = {
  ACTIVE: "active",
  ARREARS: "arrears",
  CANCELLED: "cancelled",
  PENDING_RX: "pending_rx"
};

const ORDER_STEP_LOOKUP = {
  [ORDER_STEPS.ORIGIN]: 0,
  [ORDER_STEPS.PAYMENT]: 1,
  [ORDER_STEPS.EMR]: 2,
  [ORDER_STEPS.PHARMACY]: 3,
  [ORDER_STEPS.SHIPPING]: 4,
  [ORDER_STEPS.CUSTOMER]: 5
};

module.exports = {
  EMR_STATUSES,
  ORDER_STEP_LOOKUP,
  ORDER_STEPS,
  ORDER_STATUSES,
  SHIPPING_STATUS,
  SHIPPING_STATUSES,
  SUBSCRIPTION_STATUSES
};
