// Device breakpoint keys generated by React Responsive Redux
// https://github.com/modosc/react-responsive-redux
export const RESPONSIVE_DEVICES = {
  DESKTOP: "desktop",
  TABLET: "tablet",
  PHONE: "phone"
};
