export const pharmacyTermsCopy = `
THESE TERMS AND CONDITIONS (“TERMS”) APPLY TO THE SALE AND DELIVERY OF MEDICAL CONSULTATIONS AND PRESCRIPTION MEDICATIONS THROUGH THE WEBSITE [WWW.FORHIMS.CO.UK](/) (THE “WEBSITE”).
BY CLICKING “CONFIRM ORDER”, YOU ARE AGREEING TO THESE TERMS. THESE TERMS CREATE A CONTRACT BETWEEN YOU AND HEALTH COUNTER LIMITED, COMPANY NUMBER 06646711 AND REGISTERED OFFICE AT 5 PETERWOOD PARK, PETERWOOD WAY, CROYDON, CR04UQ (“PHARMACY”) ([medicine-seller-register.mhra.gov.uk/search-registry/149](https://medicine-seller-register.mhra.gov.uk/search-registry/149)).

Pharmacy sells medical consultations and certain prescription medications through the Website. The Website is owned and operated by HIMS UK, Limited, company number 11534245 and with registered address at 4 More London, Riverside, London, United Kingdom, SE1 2AU (“HIMS UK”).  Pharmacy fills and dispenses medications through Cedarwood pharmacy registered with the General Pharmaceutical Council with number 1121830 ([pharmacyregulation.org/registers/pharmacy/registrationnumber/1121830](http://www.pharmacyregulation.org/registers/pharmacy/registrationnumber/1121830)), and provides medical consultations through Stadn Ltd, 52 High Street, Pinner, Middlesex, HA5 5PW. Superintendent Pharmacist: Yuk Shan Wong, GPhC registration number 2071680 ([pharmacyregulation.org/registers/pharmacist/registrationnumber/2071680](https://www.pharmacyregulation.org/registers/pharmacist/registrationnumber/2071680)). You can check our prescriber's registration status at any time at [cqc.org.uk/location/1-6322360454](https://www.cqc.org.uk/location/1-6322360454).

**Knowledge and Consent.** By clicking “Confirm Order”, you acknowledge that you are of the age of majority, of sound mind, and consent to these Terms with full knowledge and without undue influence or duress and that you have every opportunity to obtain independent legal advice with respect to these Terms.

**Power of Attorney.** You authorize and appoint HIMS UK as your attorney and agent, to take all steps, sign all documents, and act on your behalf as if you were personally present and acting for yourself for the limited purposes of facilitating the purchase of medical consultations and pharmaceutical products through Pharmacy. This authorization shall include but not be limited to, the collection of your personal and personal health information and the disclosure of such information to Pharmacy and any other health professionals being retained on your behalf, as required. You may revoke this authorization at any time by notifying Pharmacy in writing, but if you revoke this authorization you will not be able to purchase medical consultations or pharmaceutical products through the Website. This authorization shall continue until you revoke it.

**Prescription.** You acknowledge that the Pharmacy will not accept any order unless it receives a valid prescription
issued by a licensed physician based upon a personal consultation and examination. The Pharmacy shall present a completed questionnaire and medication request to a GMC licensed physician for the issuance of a prescription. 

**Personal Examination.** You acknowledge that you are between the ages of 18 and 65, of sound mind, and consent to these Terms with full knowledge and without undue influence or duress. You confirm that all information provided by you in the medical consultation questionnaire or elsewhere is correct and true, to the best of your knowledge. If you have trouble understanding the questionnaire, please get in contact with us. Do not answer the questionnaire until you are clear on the meaning of each question.

**Delivery.** Delivery of the pharmaceuticals you order from the Pharmacy takes place when the pharmaceuticals leave the Pharmacy. After delivery, the Pharmacy will, as attorney and agent for you, arrange for the shipping of the product to your home address. Normally, shipments take an average of 48 hours to arrive. In the event that your shipment is delayed, and upon notice from you, the Pharmacy will arrange for a replacement order to be sent to you at no additional cost. Title to the medications that you purchase passes to you when the medications leave the Pharmacy. The Pharmacy is not liable for any damages suffered due to delay in shipment or products damaged in transit.

**Warranties.** THE MANUFACTURER OF EACH PRODUCT IS SOLELY RESPONSIBLE FOR ANY WARRANTY ASSOCIATED WITH A PRODUCT. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE PHARMACY DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS OR IMPLIED, IN RESPECT OF THE PRODUCTS AND SERVICES CONTEMPLATED BY THESE TERMS AND CONDITIONS, INCLUDING, WITHOUT LIMITATION, IMPLIED
WARRANTIES AND CONDITIONS OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. RESPONSIBILITY FOR CLAIMS IN RESPECT OF THE PRODUCTS IS LIMITED TO REPLACEMENT OF THE PRODUCT.

**Privacy Policy.** You must fully and accurately disclose your personal information and consent to its use by the Pharmacy. By submitting an order to HIMS UK, you have consented to the collection and use of your personal information as described in the HIMS UK Privacy Policy (available online on the Website) and in the Pharmacy Privacy Policy (available online at [thehealthcounter.com/privacy-policy](https://www.thehealthcounter.com/privacy-policy)).
**Return Policy. The Pharmacy, does not generally accept product returns for any credit unless medications were dispensed in error contrary to the prescription. 

**Severability.** The invalidity and unenforceability of any provisions in these Terms shall not affect the validity or enforceability of any other provisions hereof and any such invalid or unenforceable provision shall be deemed to be severable.

**Headings.** The section headings used herein are for convenience of reference only and do not form a part of these Terms, and no construction or inference may be derived there from.

**Force Majeure.** The Pharmacy shall not be liable for any delay or failure in performance caused by circumstances beyond its reasonable control, including, without limitation, delays due to back orders of requested products, mail delays, or lost shipments. 

**Governing Law.** All agreements reached or contracts formed with the Pharmacy shall be deemed to have been made in the home jurisdiction of the Pharmacy (England and Wales), and the laws of that jurisdiction shall have sole and exclusive jurisdiction over any dispute arising between you and the Pharmacy.

**Contact.** You can contact the Pharmacy at [customerservice@cedarwoodpharmacy.co.uk](mailto:customerservice@cedarwoodpharmacy.co.uk) or [0203 940 6770](tel:0203-940-6770).
`;
